### ISSUE TITLE
revise description

### ISSUE THREAD

**Issue by xolotl** [creativecommons/network-platforms#5]
The overall description of this resource is a bit ungainly:
"Platforms are ways OF people to collaborate within the CC Global Network"

Could it be:
"Platforms are ways FOR people to collaborate within the CC Global Network"
or
"Platforms are ways THAT people collaborate within the CC Global Network"
?

**Comment by cablegreen** [comment]
I edited to: Platforms are organized spaces for people to collaborate across the CC Global Network
